# Generated by Django 6.0.5 on 2026-05-19 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiants', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='etudiant',
            old_name='porfolio_lien',
            new_name='portfolio_lien',
        ),
        migrations.AddField(
            model_name='etudiant',
            name='portfolio_fichier',
            field=models.FileField(blank=True, null=True, upload_to='portfolio/'),
        ),
    ]
